name: "init"
version: "0.1.0"
usage: "Initialize new chart"
description: "Initialize new chart."
command: "$HELM_PLUGIN_DIR/bin/init"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
